### ISSUE TITLE
Bugs Police (Fouille et placer objets)

### ISSUE THREAD

**Issue by MathisOReilly** [RedAlex/FiveM-NukeTown#26]
On ne peux pas fouiller personne et on ne peut pas placer d'objets (barrieres, cones et herses)

**Comment by RedAlex** [comment]
[33]-(LT-CHEF) Alex Garcio - Aujourd'hui à 13:18
@everyone 
=Fix police. La fouille ne fonctionnais plu.

=Fix police. Spawn d'object.

=Fix police. Saisie d'armes modifiais les munitions.

=Possible fix pour le drag qui sortais les gens de leur vehicule.
