### ISSUE TITLE
Serveur, #de joueur connecter 31/32 Full.

### ISSUE THREAD

**Issue by RedAlex** [RedAlex/FiveM-NukeTown#3]
Liste de joueurs et total a 31/32 serveur affiche full lors de la connection.
Bug permanent ou temporaire? 
A surveiller.

**Comment by RedAlex** [comment]
Nikki Anderson - Hier à 18:04
Bonsoir à la demande de tous je vien vous envoyer mon ''bugg'' que jai eu ! lol le server est a 31/32 et sa me ban INSTANT

**Comment by TueurSingler** [comment]
un joueu etais en instence pour sa que sa kickais auto .

**Comment by RedAlex** [comment]
Serveur a passé la soirée full 32/32
Bug temporaire.
