### ISSUE TITLE
esx_TVshow spawn vehicule et helico

### ISSUE THREAD

**Issue by tonadminprefererPB** [RedAlex/FiveM-NukeTown#31]
probleme de spawn vehicule et helico, les spawns ne marche pas. il y a un rond bleu pour le spawn de vehicule (on ne peux rien faire dedans) et le spawn dhelico sur le toit le cercle napparait pas.

**Comment by RedAlex** [comment]
https://github.com/RedAlex/FiveM-NukeTown/issues/30
