### ISSUE TITLE
Remorqueur NukeTown city 

### ISSUE THREAD

**Issue by TimaXx** [RedAlex/FiveM-NukeTown#33]
possible de réparer le QG des remorqueur svp , c'est juste la misère pour nous faire la job quand le flatbed bug ou quoi du genre 

- le menu patron bug ou ne s'affiche pas 
- le point de despawn des véhicule de s'affiche pas 
- supprimer le point de récolte pour les kit carrosserie 
- le point de spawn des flatbed bug et fait spawn le flatbed a moitier sur le bâtiment ou le point ne s'affiche pas du tout 

le flatbed bug souvent , c'est a dire que le vehicule du client reste sur le flatbed et ne peux plus dessendre

merci d'avance alex

**Comment by RedAlex** [comment]
- [Review du job remorqueur nécessaire.]

**Comment by RedAlex** [comment]
=Fix remorqueurjob nom du camion dans le menu vehicule.

=Fix remorqueurjob hashmodel

=Fix compte remorqueur sur serveur North

=Fix commande console de reboot maintenant. Serveur North

Reste a tester.

**Comment by RedAlex** [comment]
Tout est fix et tester.
