### ISSUE TITLE
Ajout : Mettre a jours les factures ambulances.

### ISSUE THREAD

**Issue by RedAlex** [RedAlex/FiveM-NukeTown#4]
Retiré une ou plusieurs balles 500$
Point de souture 200$
Plâtre 600$
Jambe(s) cassée(s) 400$
Cou cassé 800$
Prothèse quelconque 1 000$

Réanimation en hélicoptère: Réduire a 25 000 $IRM : 750$
Xray : 1000$
Soins de base : 500$
Soins d'urgence 1150$

**Comment by TueurSingler** [comment]
Medicament ? 250$

**Comment by RedAlex** [comment]
+Ajout de nouvelle factures au ambulance et rebuild du menu.
