### ISSUE TITLE
Ambulance notifications de revive hôpital

### ISSUE THREAD

**Issue by OlivierJones** [RedAlex/FiveM-NukeTown#58]
Avoir une notification quand quelqu'un revive a l'hopital, pour pas qu'on ait a se déplacer pour rien (suggéré par garcio)

**Comment by RedAlex** [comment]
+Ajout d'une notification pour les ambulanciers lors qu'un joueur décide de respawn a l'hopital au lieu de les attendres. By Alain Proviste

**Comment by EagleOnee** [comment]
Ajouter position du joueur peut etre ?
